font:
  normal:
    family: Ubuntu Mono
    style: Regular

  bold:
    family: Ubuntu Mono
    style: Bold

  italic:
    family: Ubuntu Mono
    style: Italic

  bold_italic:
    family: Ubuntu Mono
    style: Bold Italic
  size: 11

# Colors (iTerm 2 default theme)
colors:
  # Default colors
  primary:
    background: '#020200'
    foreground: '#FfFfff'

 # Normal colors
  normal:
    black:   '#3e3e3e'
    red:     '#eb4129'
    green:   '#60eE22'
    yellow:  '#ffdb24'
    blue:    '#0092DB'
    magenta: '#7b5cb0'
    cyan:    '#64dbed'
    white:   '#e5e9f0'

 # Bright colors
  bright:
    black:   '#565656'
    red:     '#f27f6f'
    green:   '#bff8a6'
    yellow:  '#fff0a7'
    blue:    '#76d1ff'
    magenta: '#a47de9'
    cyan:    '#99faf2'
    white:   '#ffffff'
